### PR TITLE
 Fixed path extension to work on a path that is created with just a bucket and no key

### PR DESCRIPTION
**Pull request by DougC**
This addresses https://github.com/lendup/fs2-blobstore/issues/36

### CODE REVIEW

**Comment by DougC** [comment]
I aimed to keep the changes as small as possible to start. It would make sense to make `Path.key` an `Option[String]` and formalise the idea that it might be absent, but that would potentially break existing uses.

**Comment by rolandomanrique** [comment]
That would make sense. I modeled `Path` from S3's `(bucket, key)` approach but it has proven to be cumbersome to handle.

Another approach would be to model `Path` as `Seq["NonEmptyString"]` and each Store impl can decide how to concatenate and handle edge cases, I think this way we could make the change without breaking backward compatibility.

**Comment by DougC** [comment]
How would you like to proceed with this? We can merge this PR and address the immediate issue, and look at other approaches, or I can make some more changes, though it might be a few days before I can get back to it.

**Comment by rolandomanrique** [comment]
@DougC I'm working with Matt to merge both open PRs and publish. We can work on improvements as a separate effort.

**Comment by DougC** [comment]
@rolandomanrique ok, thanks.

**Pull request merged**
